# Generated by Django 4.2.1 on 2023-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='comProf',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='comTrans',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='condDesCurs',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='condDesLab',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='metpredcurs',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='metpredlab',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='obiecGeneral',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='obiecSpeci',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='precondCom',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='precondCurr',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
    ]
