# Generated by Django 4.2.1 on 2023-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('telefon', models.CharField(max_length=10, null=True)),
                ('nume', models.CharField(max_length=20, null=True)),
                ('profesie', models.CharField(max_length=50, null=True)),
                ('despre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'profilul',
            },
        ),
    ]
