# Generated by Django 4.2.1 on 2023-06-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='optional',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
