# Generated by Django 4.2.1 on 2023-06-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_profil_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='optional',
        ),
    ]
