# Generated by Django 4.2.1 on 2023-06-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('pwd', models.CharField(max_length=50, null=True)),
                ('optio', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Use',
        ),
    ]
