# Generated by Django 4.2.1 on 2023-06-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='option',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
